### ISSUE TITLE
Courses with a dependency (LEC->SEM, LEC->LAB, etc) AND with more than 2 components fail to schedule

### ISSUE THREAD

**Issue by ahoskins** [rosshamish/classtime#98]
Fall Term 2015:
- [ ] ECE 304 -- [ECE 304 sections](https://dataclips.heroku.com/cbeemunjqdmhdeecznhvmcfcowww-ECE-304----Issue-rosshamishclasstime98)
- [x] ~~PSYCO 496, PSYCO 351, PHYSL 210A, PSYCO 375, PSYCO 403~~ false alarm
- [ ] MEC E 460 (MF class, this seems like it could be the issue?) -- [MEC E 460 sections](https://dataclips.heroku.com/mkovptpefdiywczpxakabzjrhjyv-MEC-E-460----Issue-rosshamishclasstime98)

Winter Term 2016:
- [ ] BIOL 207, MATH 115, STAT 252 and PSYCO 239 show no schedules (from reddit user)

Anywhere:
- [ ] EN PH 131

**Comment by zhantongz** [comment]
I also have a problem with MF + TR courses (e.g. FREN 211, SWED 111).
  * For example, a schedule with Fall 2015 FREN 211 LEC A3 (M F 11:00AM - 11:50AM AND T R 11:00AM - 12:20PM), only TR portion shows
![](https://cloud.githubusercontent.com/assets/2712994/6796348/64328696-d1e9-11e4-90dc-9abf2db6b12f.png)

**Comment by ahoskins** [comment]
Hmmm..interesting.  Here's a [data-clip](https://dataclips.heroku.com/gszxmhmdsoxkgefbagtmsmsdavrh-FREN-211) showing exactly what our database is pulling.  As you can see, MF isn't there.  

We'll have to look into this one.  These classes that don't follow the typical MWF or TR seem to be causing a few problems. :smirk:   

Thanks for letting us know about this issue @zhantongz !

**Comment by rosshamish** [comment]
Ahhhh. Now that we have this extra report I have an idea of the root cause.

**Comment by rosshamish** [comment]
> `Raghav Ramaraju`: I have a bug to report:
EN PH 131 doesn't work in any semester, even on its own. I think it might have something to do with the course name having a space in it.

**Comment by rosshamish** [comment]
Relevant dataclips:
[MEC E 460 sections](https://dataclips.heroku.com/mkovptpefdiywczpxakabzjrhjyv-MEC-E-460----Issue-rosshamishclasstime98)
[ECE 304 sections](https://dataclips.heroku.com/cbeemunjqdmhdeecznhvmcfcowww-ECE-304----Issue-rosshamishclasstime98)

**Comment by rosshamish** [comment]
I've got a good test case covering this now.

MEC E 460, ECE 304, and EN PH 131 all fail to add their Lab sections. Investigating.

**Comment by rosshamish** [comment]
Aha!

https://github.com/rosshamish/classtime/blob/master/classtime/brain/scheduling/schedule.py#L169
![image](https://cloud.githubusercontent.com/assets/1522678/6817152/83f80d54-d273-11e4-8d48-0047e633f585.png)
```
177,178: if NEITHER component has an autoEnroll (a LEC->LAB or LEC->SEM dependency)
179: then there's no dependency conflict, continue

180,181: if THESE TWO SECTIONS are dependent on each other
182: then there's no dependency conflict, continue

183: there must be a dependency conflict
```
but if there's three components in a course, and the dependent ones don't get scheduled back to back, this will fail

in the case ` BIOL 207, MATH 115, STAT 252 and PSYCO 239 show no schedules (from reddit user)`, I bet bio 207 has a lec->sem dependency

... it does. [Dataclip](https://dataclips.heroku.com/eabwsoxhizgtksradkhtnwuemddt-BIO-207----Issue-rosshamishclasstime98)

**Comment by rosshamish** [comment]
@zhantongz I've reproduced your issue, and it seems to have a different root cause than the rest of the issues in this thread, so I'm going to move it to a new issue.

**Comment by zhantongz** [comment]
@rosshamish OK #100
